Implemented find_longest_cycle(s)
brandonchinn178/circle-of-suck pull request #11
Opened 2016-11-12 21:41 UTC by thomasgreen

fixes #2

2016-11-12 22:05 UTC, brandonchinn178 requested changes
Needs tests

2016-11-12 22:05 UTC, brandonchinn178 commented on circle_suck/base/utils.py
> +    def find_all_paths(graph, start, end, path=[]):
you dont need to pass `graph` in again, since it has access to the parent's `graph` variable

2016-11-12 22:05 UTC, brandonchinn178 commented on circle_suck/base/utils.py
> +    endingindexes = []
```
[k for k, v in graph.items() if starting in v]
```

2016-11-12 22:05 UTC, brandonchinn178 commented on circle_suck/base/utils.py
> +    starting = start
why do you need this local variable?

2016-11-12 23:41 UTC, brandonchinn178 requested changes

2016-11-12 23:41 UTC, brandonchinn178 commented on circle_suck/base/utils.py
> +### TEST CASES ###
remove comments

2016-11-12 23:41 UTC, brandonchinn178 commented on circle_suck/tests/test_utils.py
> +		self.assertEqual(find_all_connected({1:[2],2:[1,5],3:[4],4:[3,5],5:[6],6:[7],7:[8],8:[6,9],9:[]}), [[8, 6, 7]])
make these a little bit pretty pls, with comments explaining what you're testing in each case.
```
season = {
    1: [2],
    2: [1, 5],
    ...
}
self.assertEqual(find_all_connected(season), [[8,6,7]])
```

2016-11-13 00:44 UTC, thomasgreen commented on circle_suck/base/utils.py
> +    starting = start
We don't.

2016-11-13 00:45 UTC, thomasgreen commented on circle_suck/base/utils.py
> +    endingindexes = []
fixed

2016-11-13 04:38 UTC, allanwlevy commented
Also fixes #12 
Additionally, for some reason, Git's saying we have a merge conflict where I don't see any merge conflict...

2016-11-13 04:42 UTC, brandonchinn178 approved these changes

2016-11-13 04:43 UTC, merged